# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
from waflib import Utils

top = '..'

def build(bld):
    test_main = bld(
        target='tests-main',
        name='tests-main',
        features='cxx',
        source='main.cpp',
        use='ChronoSync',
        defines=['BOOST_TEST_MODULE=ChronoSync']
        )

    unit_test = bld.program(
        target="../unit-tests",
        source=bld.path.ant_glob(['unit-tests/**/*.cpp']),
        features=['cxx', 'cxxprogram'],
        use='ChronoSync tests-main LOG4CXX',
        includes=['.'],
        install_path=None,
        )

    # TODO: Re-enable when there integration tests are implemented
    # integrated_test = bld.program(
    #     target="../integrated-tests",
    #     source=bld.path.ant_glob(['integrated-tests/**/*.cpp']),
    #     features=['cxx', 'cxxprogram'],
    #     use='ChronoSync tests-main',
    #     includes=['.'],
    #     install_path=None,
    #     )
